ALTER TABLE restaurants ALTER COLUMN id DROP DEFAULT;
ALTER TABLE menu_categories ALTER COLUMN id DROP DEFAULT;
ALTER TABLE menu_items ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN id DROP DEFAULT;
ALTER TABLE order_items ALTER COLUMN id DROP DEFAULT;
ALTER TABLE order_status_history ALTER COLUMN id DROP DEFAULT;
